/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import Class.DBO;
import java.awt.*;
import javax.swing.*;
import report.FrmLaporan;

public class FrmMenuUtama extends javax.swing.JFrame {
    
    private boolean append;
    Dimension parentSize = this.getSize();
    /**
     * Creates new form frmMenuUtama
     */
    public FrmMenuUtama() {
        initComponents();
        settingkoneksi();
        setSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
    }
    
    private void settingkoneksi() {
        DBO setting = new DBO();
        setting.makeConnect();
        if (setting.isConnected() == true) {
            JOptionPane.showMessageDialog(null, "Terhubung dengan Database");
        } else {
            JOptionPane.showMessageDialog(null, "Koneksi database gagal ");
        }
    }
    
    private void linkuser() {
        mstr_user._List fus = new mstr_user._List();
        fus = new mstr_user._List();
        jDesktopPane1.add(fus);
        Dimension parentSize = this.getSize();
        Dimension childSize = fus.getSize();
        // Menghitung posisi X dan Y agar jendela berada di tengah
        fus.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        fus.setVisible(true);
    }

    private void linkcust() {
        mstr_customer._List fu = new mstr_customer._List();
        fu = new mstr_customer._List();
        jDesktopPane1.add(fu);
        Dimension parentSize = this.getSize();
        Dimension childSize = fu.getSize();
        // Menghitung posisi X dan Y agar jendela berada di tengah
        fu.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        fu.setVisible(true);
    }

    private void linkproduk() {
        mstr_product._List fp = new mstr_product._List();
        fp = new mstr_product._List(); // Baris ini redundan, objek sudah dibuat di baris sebelumnya.
        jDesktopPane1.add(fp);
        Dimension parentSize = this.getSize();
        Dimension childSize = fp.getSize();
        // Menghitung posisi X dan Y agar jendela berada di tengah
        fp.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        fp.setVisible(true);
    }

    private void linkpenjualan() {
        ttrs_penjualan._List ftp = new ttrs_penjualan._List();
        ftp = new ttrs_penjualan._List(); // Baris ini redundan.
        jDesktopPane1.add(ftp);
        Dimension parentSize = this.getSize();
        Dimension childSize = ftp.getSize();
        // Menghitung posisi X dan Y agar jendela berada di tengah
        ftp.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        ftp.setVisible(true);
    }
    
    private void LFrmCustomer() {
        FrmLaporan l = new FrmLaporan();
        jDesktopPane1.add(l);
        Dimension parentSize = this.getSize();
        Dimension childSize = l.getSize();
        // Menghitung posisi X dan Y agar jendela berada di tengah
        l.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        l.setVisible(true);
        l.btampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.btampil.setText("Cetak Data Customer");
            }
        });
    }
    
    private void LFrmUser() {
        FrmLaporan l = new FrmLaporan();
        jDesktopPane1.add(l);
        Dimension parentSize = this.getSize();
        Dimension childSize = l.getSize();
        // Menghitung posisi X dan Y agar jendela berada di tengah
        l.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        l.setVisible(true);
        l.btampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.btampil.setText("Cetak Data User");
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SU_Login = new javax.swing.JMenuItem();
        SU_Logout = new javax.swing.JMenuItem();
        SU_Keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        m_user = new javax.swing.JMenuItem();
        m_customer = new javax.swing.JMenuItem();
        m_product = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ttrs_penjualan = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        l_cust = new javax.swing.JMenuItem();
        l_user = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Switch User");

        SU_Login.setText("Login");
        SU_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SU_LoginActionPerformed(evt);
            }
        });
        jMenu1.add(SU_Login);

        SU_Logout.setText("Logout");
        SU_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SU_LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(SU_Logout);

        SU_Keluar.setText("Keluar");
        SU_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SU_KeluarActionPerformed(evt);
            }
        });
        jMenu1.add(SU_Keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        m_user.setText("Master User");
        m_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_userActionPerformed(evt);
            }
        });
        jMenu2.add(m_user);

        m_customer.setText("Master Customer");
        m_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_customerActionPerformed(evt);
            }
        });
        jMenu2.add(m_customer);

        m_product.setText("Master Product");
        m_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_productActionPerformed(evt);
            }
        });
        jMenu2.add(m_product);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        ttrs_penjualan.setText("Transaksi Penjualan");
        ttrs_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttrs_penjualanActionPerformed(evt);
            }
        });
        jMenu3.add(ttrs_penjualan);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");

        l_cust.setText("Laporan Customer");
        l_cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_custActionPerformed(evt);
            }
        });
        jMenu4.add(l_cust);

        l_user.setText("Laporan User");
        l_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_userActionPerformed(evt);
            }
        });
        jMenu4.add(l_user);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SU_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SU_LoginActionPerformed
        FrmLogin fl = new FrmLogin();
        Dimension parentSize = this.getSize();
        Dimension childSize = fl.getSize();
        // Menghitung posisi X dan Y agar jendela berada di tengah
        fl.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        fl.setVisible(true);
    }//GEN-LAST:event_SU_LoginActionPerformed

    private void SU_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SU_LogoutActionPerformed
        append = false;
        this.setVisible(append);
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_SU_LogoutActionPerformed

    private void SU_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SU_KeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SU_KeluarActionPerformed

    private void m_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_userActionPerformed
        linkuser();
    }//GEN-LAST:event_m_userActionPerformed

    private void m_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_customerActionPerformed
        linkcust();
    }//GEN-LAST:event_m_customerActionPerformed

    private void m_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_productActionPerformed
        linkproduk();
    }//GEN-LAST:event_m_productActionPerformed

    private void ttrs_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttrs_penjualanActionPerformed
        linkpenjualan();
    }//GEN-LAST:event_ttrs_penjualanActionPerformed

    private void l_custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_custActionPerformed
        LFrmCustomer();
    }//GEN-LAST:event_l_custActionPerformed

    private void l_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_userActionPerformed
        LFrmUser();
    }//GEN-LAST:event_l_userActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SU_Keluar;
    private javax.swing.JMenuItem SU_Login;
    private javax.swing.JMenuItem SU_Logout;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem l_cust;
    private javax.swing.JMenuItem l_user;
    private javax.swing.JMenuItem m_customer;
    private javax.swing.JMenuItem m_product;
    private javax.swing.JMenuItem m_user;
    private javax.swing.JMenuItem ttrs_penjualan;
    // End of variables declaration//GEN-END:variables
}
